"""add stage message to task tracker

Revision ID: ccfb3531a067
Revises: 0c0e9f9aa378
Create Date: 2026-06-04 02:48:43.558309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfb3531a067'
down_revision: Union[str, None] = '0c0e9f9aa378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_trackers', sa.Column('stage', sa.String(length=100), nullable=True))
    op.add_column('task_trackers', sa.Column('message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_trackers', 'message')
    op.drop_column('task_trackers', 'stage')
    # ### end Alembic commands ###
